# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build settings (not needed for static site, but good to have)
  publish = "."
  
[build.environment]
  # Environment for build process
  NODE_VERSION = "18"

# Headers for optimal caching and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for HTML (short cache)
    Cache-Control = "public, max-age=300, s-maxage=300"

# CSS and JS files - longer cache with versioning
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Images - long cache
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects (if needed in the future)
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301
